# Catppuccin Macchiato Lavender

code_syntax_highlight = "catppuccin-macchiato"

file_panel_border = "#6e738d"
sidebar_border = "#24273a"
footer_border = "#6e738d"
file_panel_border_active = "#b7bdf8"
sidebar_border_active = "#b7bdf8"
footer_border_active = "#b7bdf8"
modal_border_active = "#6e738d"
full_screen_bg = "#24273a"
file_panel_bg = "#24273a"
sidebar_bg = "#24273a"
footer_bg = "#24273a"
modal_bg = "#24273a"
full_screen_fg = "#a5adcb"
file_panel_fg = "#a5adcb"
sidebar_fg = "#a5adcb"
footer_fg = "#a5adcb"
modal_fg = "#a5adcb"
cursor = "#f4dbd6"
correct = "#a6da95"
error = "#ed8796"
hint = "#91d7e3"
cancel = "#f5bde6"
gradient_color = ["#8aadf4", "#c6a0f6"]
directory_icon_color = "#8aadf4"
file_panel_top_directory_icon = "#a6da95"
file_panel_top_path = "#8aadf4"
file_panel_item_selected_fg = "#b7bdf8"
file_panel_item_selected_bg = "#24273a"
sidebar_title = "#91d7e3"
sidebar_item_selected_fg = "#b7bdf8"
sidebar_item_selected_bg = "#24273a"
sidebar_divider = "#6e738d"
modal_cancel_fg = "#363a4f"
modal_cancel_bg = "#f5bde6"
modal_confirm_fg = "#363a4f"
modal_confirm_bg = "#91d7e3"
help_menu_hotkey = "#91d7e3"
help_menu_title = "#f5bde6"
