# Catppuccin Latte Red

code_syntax_highlight = "catppuccin-latte"

file_panel_border = "#9ca0b0"
sidebar_border = "#eff1f5"
footer_border = "#9ca0b0"
file_panel_border_active = "#d20f39"
sidebar_border_active = "#d20f39"
footer_border_active = "#d20f39"
modal_border_active = "#9ca0b0"
full_screen_bg = "#eff1f5"
file_panel_bg = "#eff1f5"
sidebar_bg = "#eff1f5"
footer_bg = "#eff1f5"
modal_bg = "#eff1f5"
full_screen_fg = "#6c6f85"
file_panel_fg = "#6c6f85"
sidebar_fg = "#6c6f85"
footer_fg = "#6c6f85"
modal_fg = "#6c6f85"
cursor = "#dc8a78"
correct = "#40a02b"
error = "#d20f39"
hint = "#04a5e5"
cancel = "#ea76cb"
gradient_color = ["#1e66f5", "#8839ef"]
directory_icon_color = "#1e66f5"
file_panel_top_directory_icon = "#40a02b"
file_panel_top_path = "#1e66f5"
file_panel_item_selected_fg = "#d20f39"
file_panel_item_selected_bg = "#eff1f5"
sidebar_title = "#04a5e5"
sidebar_item_selected_fg = "#d20f39"
sidebar_item_selected_bg = "#eff1f5"
sidebar_divider = "#9ca0b0"
modal_cancel_fg = "#ccd0da"
modal_cancel_bg = "#ea76cb"
modal_confirm_fg = "#ccd0da"
modal_confirm_bg = "#04a5e5"
help_menu_hotkey = "#04a5e5"
help_menu_title = "#ea76cb"
