# Catppuccin Frapp√© Blue

code_syntax_highlight = "catppuccin-frappe"

file_panel_border = "#737994"
sidebar_border = "#303446"
footer_border = "#737994"
file_panel_border_active = "#8caaee"
sidebar_border_active = "#8caaee"
footer_border_active = "#8caaee"
modal_border_active = "#737994"
full_screen_bg = "#303446"
file_panel_bg = "#303446"
sidebar_bg = "#303446"
footer_bg = "#303446"
modal_bg = "#303446"
full_screen_fg = "#a5adce"
file_panel_fg = "#a5adce"
sidebar_fg = "#a5adce"
footer_fg = "#a5adce"
modal_fg = "#a5adce"
cursor = "#f2d5cf"
correct = "#a6d189"
error = "#e78284"
hint = "#99d1db"
cancel = "#f4b8e4"
gradient_color = ["#8caaee", "#ca9ee6"]
directory_icon_color = "#8caaee"
file_panel_top_directory_icon = "#a6d189"
file_panel_top_path = "#8caaee"
file_panel_item_selected_fg = "#8caaee"
file_panel_item_selected_bg = "#303446"
sidebar_title = "#99d1db"
sidebar_item_selected_fg = "#8caaee"
sidebar_item_selected_bg = "#303446"
sidebar_divider = "#737994"
modal_cancel_fg = "#414559"
modal_cancel_bg = "#f4b8e4"
modal_confirm_fg = "#414559"
modal_confirm_bg = "#99d1db"
help_menu_hotkey = "#99d1db"
help_menu_title = "#f4b8e4"
